name: New Release
on: 
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make some file
        run: date > build/file.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/file.txt
          
      - name: Create the new release
        run: gh release create v1.0.0 '/build/file.txt#Released File'
